"""
NR-AutoAuditor レポート生成モジュール
日次監査結果を Markdown レポートとして出力する。
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from models import AuditResult, AuditStatus, DailyReport

logger = logging.getLogger(__name__)


def generate_markdown_report(report: DailyReport, output_dir: Path) -> Path:
    """日次監査レポートを Markdown ファイルとして生成"""
    filename = f"audit_report_{report.date}.md"
    filepath = output_dir / filename

    lines: list[str] = []

    # ヘッダー
    lines.append(f"# NR-AutoAuditor 監査レポート — {report.date}")
    lines.append("")
    lines.append(f"実行時刻: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"所要時間: {report.elapsed_seconds:.1f}秒")
    lines.append("")

    # サマリー
    lines.append("## サマリー")
    lines.append("")
    lines.append("| 項目 | 件数 |")
    lines.append("|------|------|")
    lines.append(f"| 総問題数 | {report.total_questions} |")
    lines.append(f"| OK | {report.ok_count} |")
    lines.append(f"| WARNING | {report.warning_count} |")
    lines.append(f"| ERROR | {report.error_count} |")
    lines.append(f"| 自動修正済み | {report.auto_fixed_count} |")
    lines.append(f"| 修正検証済み | {report.fix_verified_count} |")
    lines.append("")

    # カテゴリ別内訳
    if report.categories:
        lines.append("## カテゴリ別問題数")
        lines.append("")
        lines.append("| カテゴリ | 問題数 |")
        lines.append("|----------|--------|")
        for cat, count in sorted(report.categories.items()):
            lines.append(f"| {cat} | {count} |")
        lines.append("")

    # ERROR 詳細
    errors = [r for r in report.results if r.status == AuditStatus.ERROR]
    if errors:
        lines.append("## ERROR 一覧")
        lines.append("")
        for r in errors:
            lines.append(f"### {r.question_id} ({r.category})")
            lines.append(f"- 信頼度: {r.confidence:.2f}")
            lines.append(f"- 修正適用: {'済' if r.fix_applied else '未'}")
            if r.issues:
                lines.append("- 問題点:")
                for issue in r.issues:
                    lines.append(f"  - {issue}")
            if r.fix_suggestions:
                lines.append("- 修正提案:")
                for fs in r.fix_suggestions:
                    lines.append(f"  - `{fs.field}`: `{fs.current}` → `{fs.suggested}`")
            if r.reasoning:
                lines.append(f"- 理由: {r.reasoning[:200]}")
            lines.append("")

    # WARNING 詳細（上位20件まで）
    warnings = [r for r in report.results if r.status == AuditStatus.WARNING]
    if warnings:
        lines.append("## WARNING 一覧（上位20件）")
        lines.append("")
        for r in warnings[:20]:
            lines.append(f"### {r.question_id} ({r.category})")
            lines.append(f"- 信頼度: {r.confidence:.2f}")
            if r.issues:
                lines.append("- 問題点:")
                for issue in r.issues:
                    lines.append(f"  - {issue}")
            lines.append("")
        if len(warnings) > 20:
            lines.append(f"*他 {len(warnings) - 20} 件省略*")
            lines.append("")

    # フッター
    lines.append("---")
    lines.append("*Generated by NR-AutoAuditor*")

    content = "\n".join(lines)
    filepath.write_text(content, encoding="utf-8")
    logger.info("レポート生成完了: %s", filepath)
    return filepath


def build_report(
    results: list[AuditResult],
    elapsed: float,
) -> DailyReport:
    """監査結果リストから DailyReport を構築"""
    today = datetime.now().strftime("%Y-%m-%d")

    # カテゴリ別集計
    categories: dict[str, int] = {}
    for r in results:
        categories[r.category] = categories.get(r.category, 0) + 1

    return DailyReport(
        date=today,
        total_questions=len(results),
        ok_count=sum(1 for r in results if r.status == AuditStatus.OK),
        warning_count=sum(1 for r in results if r.status == AuditStatus.WARNING),
        error_count=sum(1 for r in results if r.status == AuditStatus.ERROR),
        auto_fixed_count=sum(1 for r in results if r.fix_applied),
        fix_verified_count=sum(1 for r in results if r.fix_verified),
        elapsed_seconds=elapsed,
        categories=categories,
        results=results,
    )


def format_notification_summary(report: DailyReport) -> str:
    """通知用の短いサマリーテキストを生成"""
    emoji = "✅" if report.error_count == 0 else "🚨"
    lines = [
        f"{emoji} NR-AutoAuditor 日次レポート ({report.date})",
        f"総問題数: {report.total_questions}",
        f"OK: {report.ok_count} / WARNING: {report.warning_count} / ERROR: {report.error_count}",
    ]
    if report.auto_fixed_count:
        lines.append(f"自動修正: {report.auto_fixed_count}件")
    lines.append(f"所要時間: {report.elapsed_seconds:.0f}秒")
    return "\n".join(lines)
