// questions_extra.js — 追加問題 g1048–g1067 (20問)
// 時制・冠詞・前置詞・関係詞・比較・仮定法・動名詞・受動態・使役・分詞など
DATA.push(
  { id: "g1048", diff: "lv2", axis: "tense", tags: ["eiken3", "present_perfect"], stem: "She ___ to Paris twice.", ja: "彼女はパリに2回行ったことがある。", answer: "has been", choices: ["has been", "went", "goes", "had been", "was"], expl: "「2回行ったことがある」は経験を表す現在完了形。have been to + 場所＝〜へ行ったことがある。", rule: "現在完了（経験）have + 過去分詞", kp: ["経験のhave been to", "twiceなどの経験回数と現在完了"] },
  { id: "g1049", diff: "lv2", axis: "form", tags: ["eiken3", "articles"], stem: "I saw ___ elephant at the zoo yesterday.", ja: "昨日、動物園でゾウを1頭見た。", answer: "an", choices: ["an", "a", "the", "one", "some"], expl: "elephantは母音（e）で始まるので不定冠詞はan。初出の単数可算名詞には不定冠詞をつける。", rule: "不定冠詞 a / an の使い分け（母音・子音）", kp: ["母音で始まる語の前はan", "子音で始まる語の前はa"] },
  { id: "g1050", diff: "lv2", axis: "vocab", tags: ["eiken3", "preposition"], stem: "He arrived ___ the airport two hours before departure.", ja: "彼は出発の2時間前に空港に到着した。", answer: "at", choices: ["at", "in", "to", "on", "into"], expl: "arriveの後の前置詞は地点にはat、広い場所（国・都市）にはin。airportは特定の地点なのでat。", rule: "arrive at（地点）vs arrive in（広い場所）", kp: ["arrive at + 特定の場所", "arrive in + 都市・国"] },
  { id: "g1051", diff: "lv2", axis: "form", tags: ["eiken3", "relative"], stem: "The woman ___ lives next door is a nurse.", ja: "隣に住んでいる女性は看護師です。", answer: "who", choices: ["who", "which", "whose", "whom", "that"], expl: "先行詞がthe woman（人）で、関係節内で主語の役割をするのでwho。", rule: "主格の関係代名詞 who（人）/ which（物）", kp: ["先行詞が人 → who", "先行詞が物 → which"] },
  { id: "g1052", diff: "lv2", axis: "tense", tags: ["eiken3", "past_progressive"], stem: "I ___ TV when she called me.", ja: "彼女が電話してきたとき、私はテレビを見ていた。", answer: "was watching", choices: ["was watching", "watched", "watch", "am watching", "had watched"], expl: "when she calledが過去の一時点。そのとき進行中だった動作には過去進行形（was + -ing）を使う。", rule: "過去進行形 was/were + -ing", kp: ["whenで始まる過去の一時点と進行形", "過去の継続中の動作はwas/were + -ing"] },
  { id: "g1053", diff: "lv2", axis: "form", tags: ["eiken3", "comparison"], stem: "Mt. Fuji is ___ mountain in Japan.", ja: "富士山は日本で最も高い山です。", answer: "the highest", choices: ["the highest", "higher", "high", "most high", "the most high"], expl: "3つ以上の比較でthe + 最上級（-est）を使う。tallやhighのように短い形容詞は-estで最上級を作る。", rule: "最上級 the + -est（短い形容詞）", kp: ["最上級はtheをつける", "1・2音節の形容詞は-est形"] },
  { id: "g1054", diff: "lv3", axis: "form", tags: ["eiken2", "subjunctive"], stem: "If I ___ you, I would study harder.", ja: "もし私があなたなら、もっと一生懸命勉強するのに。", answer: "were", choices: ["were", "was", "am", "be", "would be"], expl: "現実に反する仮定（仮定法過去）では、be動詞はすべての人称でwereを使う。", rule: "仮定法過去 If + S + were / 動詞の過去形", kp: ["仮定法過去のbe動詞はwere（全人称）", "現在の事実に反する仮定"] },
  { id: "g1055", diff: "lv3", axis: "form", tags: ["eiken2", "gerund"], stem: "She enjoys ___ classical music in the evening.", ja: "彼女は夜にクラシック音楽を聴くのを楽しんでいる。", answer: "listening to", choices: ["listening to", "to listen to", "listen to", "listened to", "to listening"], expl: "enjoyの後には動名詞（-ing形）が続く。enjoyの後に不定詞は来ない。", rule: "動名詞のみを目的語にとる動詞（enjoy, finish, mind など）", kp: ["enjoy + 動名詞（-ing）", "enjoyの後にto不定詞は不可"] },
  { id: "g1056", diff: "lv3", axis: "form", tags: ["eiken2", "passive"], stem: "This novel ___ by millions of readers around the world.", ja: "この小説は世界中で何百万もの読者に読まれている。", answer: "is read", choices: ["is read", "reads", "is reading", "read", "has read"], expl: "主語This novelは読む側でなく読まれる側。現在の事実を表す受動態はis + 過去分詞。", rule: "受動態 be動詞 + 過去分詞", kp: ["受動態はbe + 過去分詞", "主語が動作を受ける立場"] },
  { id: "g1057", diff: "lv3", axis: "tense", tags: ["eiken2", "past_perfect"], stem: "By the time he arrived, she ___ already left.", ja: "彼が到着したとき、彼女はすでに出発していた。", answer: "had", choices: ["had", "has", "have", "was", "did"], expl: "by the timeの節（彼が到着した）よりもさらに前の出来事には過去完了形（had + 過去分詞）を使う。", rule: "過去完了 had + 過去分詞（過去のある時点より前の出来事）", kp: ["by the time + 過去形 → 過去完了", "過去完了は過去のある時点より前を表す"] },
  { id: "g1058", diff: "lv3", axis: "vocab", tags: ["eiken2", "preposition", "fixed_phrase"], stem: "She is very interested ___ learning Japanese culture.", ja: "彼女は日本文化を学ぶことに非常に興味がある。", answer: "in", choices: ["in", "at", "for", "about", "on"], expl: "be interested in〜で「〜に興味がある」という固定表現。前置詞inの後は名詞または動名詞。", rule: "be interested in + 名詞 / 動名詞", kp: ["be interested in は固定表現", "inの後は名詞か動名詞"] },
  { id: "g1059", diff: "lv3", axis: "form", tags: ["eiken2", "causative"], stem: "She had the mechanic ___ her car before the trip.", ja: "彼女は旅行前に整備士に車を点検させた。", answer: "check", choices: ["check", "to check", "checking", "checked", "to checking"], expl: "have + O + 動詞の原形（使役）で「Oに〜させる」。目的語が人の場合は動詞の原形が続く。", rule: "使役動詞 have + O + 原形（人に〜させる）", kp: ["have + 人 + 原形 = 〜させる", "目的語が物の場合はhave + 物 + 過去分詞"] },
  { id: "g1060", diff: "lv3", axis: "logic", tags: ["eiken2", "conjunction"], stem: "___ he was tired, he continued working until midnight.", ja: "疲れていたにもかかわらず、彼は深夜まで働き続けた。", answer: "Although", choices: ["Although", "Because", "If", "Since", "Unless"], expl: "前半（疲れていた）と後半（働き続けた）は逆接の関係。逆接の接続詞はAlthough（〜にもかかわらず）。", rule: "逆接の接続詞 although / even though", kp: ["although＝〜にもかかわらず（逆接）", "because＝〜なので（理由）との混同に注意"] },
  { id: "g1061", diff: "lv3", axis: "form", tags: ["eiken2", "modal"], stem: "You ___ not smoke inside the building. It is strictly prohibited.", ja: "建物内での喫煙は禁止されています。", answer: "must", choices: ["must", "should", "might", "can", "would"], expl: "must not は強い禁止を表す。should notは「すべきでない」という助言。strictly prohibitedとの文脈からmust notが適切。", rule: "must not（禁止）vs should not（助言）", kp: ["must not = 禁止（〜してはならない）", "should not = 〜すべきでない"] },
  { id: "g1062", diff: "lv4", axis: "form", tags: ["eikenpre1", "inversion"], stem: "Not only ___ the first prize, but he also received a special award.", ja: "彼は1位を獲得しただけでなく、特別賞も受賞した。", answer: "did he win", choices: ["did he win", "he won", "he did win", "won he", "has he win"], expl: "Not onlyが文頭に来るとき、主語と助動詞は倒置（did he win）する。", rule: "否定副詞句が文頭に来ると主語・助動詞が倒置される", kp: ["Not only...but also の倒置形", "否定表現が文頭 → 疑問文の語順"] },
  { id: "g1063", diff: "lv4", axis: "tense", tags: ["eikenpre1", "future_perfect"], stem: "By next April, she ___ at this company for ten years.", ja: "来年4月までに、彼女はこの会社に10年間勤めたことになる。", answer: "will have worked", choices: ["will have worked", "will work", "has worked", "will be working", "would work"], expl: "by next Aprilは未来の期限。その時点で完了している動作には未来完了形（will have + 過去分詞）を使う。", rule: "未来完了 will have + 過去分詞（未来の時点での完了）", kp: ["by + 未来の時点 → 未来完了", "will have + 過去分詞"] },
  { id: "g1064", diff: "lv4", axis: "form", tags: ["eikenpre1", "subjunctive_present"], stem: "It is essential that every employee ___ the safety manual.", ja: "すべての従業員が安全マニュアルを読むことが不可欠だ。", answer: "read", choices: ["read", "reads", "reading", "to read", "should reads"], expl: "It is essential that節（要求・主張・提案・義務を示す形容詞に続くthat節）では、動詞は主語に関わらず原形（仮定法現在）を使う。", rule: "that節の仮定法現在（要求・義務を示す形容詞 + that + S + 動詞の原形）", kp: ["essential / necessary / important + that + 動詞の原形", "三単現のsは不要"] },
  { id: "g1065", diff: "lv4", axis: "logic", tags: ["eikenpre1", "participle"], stem: "___ from above, the ancient ruins formed a perfect circle.", ja: "上から見ると、その古代遺跡は完全な円を形成していた。", answer: "Seen", choices: ["Seen", "Seeing", "To see", "Having seen", "See"], expl: "主語the ancient ruinsは「見られる」立場（受動）。受動の意味を持つ分詞構文は過去分詞（Seen）で始まる。", rule: "受動の分詞構文は過去分詞で始まる", kp: ["主語が〜される関係 → 過去分詞で分詞構文", "Seen from... = 〜から見ると"] },
  { id: "g1066", diff: "lv2", axis: "vocab", tags: ["eiken3", "preposition", "time"], stem: "She has been studying English ___ she was in elementary school.", ja: "彼女は小学生のころからずっと英語を勉強している。", answer: "since", choices: ["since", "for", "during", "from", "while"], expl: "「〜からずっと」は起点を示すsince + 過去の時点。forは「〜の間」という期間の長さを表す。", rule: "since + 起点（時点）vs for + 期間の長さ", kp: ["since + 過去の時点（いつから）", "for + 数字/期間（どれだけの間）"] },
  { id: "g1067", diff: "lv3", axis: "form", tags: ["eiken2", "relative", "whose"], stem: "I helped a woman ___ car had broken down on the highway.", ja: "高速道路で車が故障した女性を助けた。", answer: "whose", choices: ["whose", "who", "which", "that", "whom"], expl: "先行詞a womanと、関係節内のcar（名詞）の所有関係を示すには所有格の関係代名詞whoseを使う。", rule: "所有格の関係代名詞 whose（人・物の所有を表す）", kp: ["whose + 名詞 = 〜の（所有）", "人・物どちらの先行詞にも使える"] }
);
