// questions_extra2.js — 追加問題 g1578–g1592 (15問)
// 比較・受動態・関係詞・現在完了・不定詞・動名詞・助動詞・条件文・仮定法・倒置など
DATA.push(
  { id: "g1578", diff: "lv2", axis: "form", tags: ["eiken3", "comparative"], stem: "This problem is ___ than I thought.", ja: "この問題は思っていたより難しい。", answer: "more difficult", choices: ["more difficult", "most difficult", "difficulter", "the most difficult", "as difficult"], expl: "比較級: more + 多音節形容詞（difficult など）を使って「〜よりも」を表す。more difficult than = 「〜よりも難しい」。difficulter は誤った形（difficult は規則変化せず more/most を使う）。most difficult / the most difficult は最上級。as difficult は同等比較（as...as）。", rule: "比較級: more + 形容詞 + than（多音節形容詞の比較）", kp: ["more difficult than = 〜よりも難しい（比較級）", "difficult → more difficult → most difficult（規則変化しない形容詞は more/most）"] },
  { id: "g1579", diff: "lv2", axis: "form", tags: ["eiken3", "passive_voice"], stem: "The report ___ by the manager yesterday.", ja: "その報告書は昨日マネージャーによって書かれた。", answer: "was written", choices: ["was written", "wrote", "is written", "has written", "had write"], expl: "受動態の過去形: was/were + 過去分詞 + by + 行為者。was written = 「書かれた」（過去の受動態）。wrote は能動態の過去形（主語が書いた、になる）。is written は現在形の受動態。has written は現在完了能動態。had write は誤り（過去完了は had + pp）。", rule: "受動態の過去形: was/were + 過去分詞（〜された）", kp: ["was written by... = 〜によって書かれた（過去の受動態）", "受動態: be動詞（時制に合わせる）+ 過去分詞"] },
  { id: "g1580", diff: "lv2", axis: "logic", tags: ["eiken3", "relative_pronoun"], stem: "The woman ___ lives next door is a doctor.", ja: "隣に住んでいる女性は医者だ。", answer: "who", choices: ["who", "which", "what", "whose", "whom"], expl: "関係代名詞 who: 先行詞が人（the woman）で、関係節内で主語の役割を果たす場合は who を使う。which は物・動物の場合。what は先行詞を含む関係代名詞（the thing that）。whose は所有を表す（whose house = 〜の家）。whom は目的語を表す（who の目的格）。", rule: "関係代名詞 who：先行詞が人 + 関係節内で主語の役割", kp: ["who lives next door = 隣に住んでいる（先行詞=人、主格）", "who（人・主格）/ whom（人・目的格）/ which（物）/ whose（所有）"] },
  { id: "g1581", diff: "lv2", axis: "tense", tags: ["eiken3", "present_perfect_experience"], stem: "I ___ visited Japan three times.", ja: "私は日本を3回訪れたことがある。", answer: "have", choices: ["have", "had", "am", "did", "was"], expl: "現在完了形（経験）: have/has + 過去分詞。I have visited = 「訪れたことがある」（経験を表す現在完了）。times（回数）と組み合わせて経験の回数を示す。had visited は過去完了（別の過去の基準点より前の経験）。am visited は受動態（意味不明）。did visited は誤り（did の後は動詞原形）。was visited は受動態の過去（訪問された）。", rule: "現在完了（経験）: have/has + pp（〜したことがある）", kp: ["have visited three times = 3回訪れたことがある（現在完了・経験）", "経験の表現: have + pp + times/before/ever/never"] },
  { id: "g1582", diff: "lv2", axis: "form", tags: ["eiken3", "infinitive_purpose"], stem: "She went to the store ___ some milk.", ja: "彼女は牛乳を買うために店に行った。", answer: "to buy", choices: ["to buy", "buying", "bought", "buy", "for buying"], expl: "不定詞の副詞的用法（目的）: to + 動詞原形 = 「〜するために」。to buy = 「買うために」（目的）。buying は現在分詞（went buying = 買い物に行くパターンもあるが to buy の方が自然）。bought は過去形（動詞が並んでしまう）。buy だけでは文法的につながらない。for buying は for + 動名詞（理由・目的を表すこともあるが to 不定詞の方が一般的）。", rule: "to不定詞（副詞的用法・目的）：to + 動詞原形 = 〜するために", kp: ["went to the store to buy = 買うために店に行った（目的のto不定詞）", "目的を表す: to + 動詞原形（最も一般的）/ in order to（より明示的）"] },
  { id: "g1583", diff: "lv2", axis: "form", tags: ["eiken3", "gerund_subject"], stem: "___ English every day is the best way to improve.", ja: "毎日英語を話すことが上達への最善の方法だ。", answer: "Speaking", choices: ["Speaking", "To speak", "Speak", "Spoken", "Speaks"], expl: "動名詞（主語）: 動名詞(-ing形)は名詞として主語になる。Speaking English every day = 「毎日英語を話すこと」（主語）。To speak も不定詞の名詞的用法として正しいが、ここでは動名詞が求められている。Speak は動詞原形（主語にはなれない）。Spoken は過去分詞（主語の役割を果たさない）。Speaks は三人称単数現在形（主語として不適切）。", rule: "動名詞（主語）：動詞 + -ing = 〜すること（主語の役割）", kp: ["Speaking English = 英語を話すこと（動名詞が主語）", "動名詞 vs 不定詞：どちらも主語になれるが、動名詞の方が一般的・慣用的"] },
  { id: "g1584", diff: "lv2", axis: "logic", tags: ["eiken3", "modal_should_advice"], stem: "You ___ see a doctor if you feel sick.", ja: "気分が悪ければ医者に診てもらうべきだ。", answer: "should", choices: ["should", "must", "can", "might", "will"], expl: "should = 〜すべき（アドバイス・勧告）。You should see a doctor = 「医者に診てもらうべきだ」（強制ではなく、アドバイスとして）。must = 〜しなければならない（義務・強制）。can = 〜できる（能力・許可）。might = 〜かもしれない（推量・可能性）。will = 〜するだろう（意志・予測）。アドバイスの文脈から should が適切。", rule: "should：〜すべき（アドバイス・勧告・控えめな義務）", kp: ["should see a doctor = 医者に診てもらうべき（should = アドバイス）", "should（アドバイス）/ must（強い義務）/ had better（〜した方がよい、警告含む）"] },
  { id: "g1585", diff: "lv2", axis: "logic", tags: ["eiken3", "first_conditional"], stem: "If it ___ tomorrow, we will cancel the picnic.", ja: "もし明日雨が降れば、ピクニックをキャンセルする。", answer: "rains", choices: ["rains", "will rain", "rained", "rain", "would rain"], expl: "第1条件文（現実的な条件）: If + 現在形, will + 動詞原形。if節の中では will を使わず現在形を使う。If it rains = 「もし雨が降れば」（条件節は現在形）。will rain は条件節内では通常使わない。rained は過去形（仮定法過去の場合）。rain は原形（三人称単数には -s が必要）。would rain は仮定法過去の帰結節。", rule: "第1条件文：If + 現在形, will + 動詞原形（実現可能な条件）", kp: ["If it rains = もし雨が降れば（条件節: if + 現在形）", "第1条件文: If + 現在形 → will + 動詞原形（実現の可能性あり）"] },
  { id: "g1586", diff: "lv3", axis: "logic", tags: ["eiken2", "second_conditional"], stem: "If I ___ a million dollars, I would travel the world.", ja: "もし100万ドルあれば、世界を旅するのに。", answer: "had", choices: ["had", "have", "would have", "will have", "have had"], expl: "仮定法過去（第2条件文）: If + 過去形, would + 動詞原形。現実には持っていないが、もし持っていれば〜という仮想の状況。If I had = 「もし持っていれば」（仮定法過去: 現在の事実に反する仮定）。have は直説法現在（実際に持っている場合）。would have は帰結節の形（条件節には使わない）。will have は未来完了（仮定法ではない）。have had は現在完了（仮定法過去ではない）。", rule: "仮定法過去：If + 過去形, would + 動詞原形（現在の事実に反する仮定）", kp: ["If I had a million dollars = もし100万ドルあれば（仮定法過去: 現実には持っていない）", "仮定法過去 vs 第1条件文: If I had（非現実）/ If I have（現実の可能性）"] },
  { id: "g1587", diff: "lv2", axis: "logic", tags: ["eiken3", "indirect_question"], stem: "Could you tell me ___ the bank is?", ja: "銀行がどこにあるか教えていただけますか？", answer: "where", choices: ["where", "if", "that", "what", "which"], expl: "間接疑問文: 疑問詞 + 主語 + 動詞の語順（直接疑問文の語順と逆）。where the bank is = 「銀行がどこにあるか」（間接疑問文: where + S + V）。if は yes/no 疑問の間接疑問（if the bank is... は意味が不明確）。that は名詞節を導く接続詞（疑問の意味がない）。what は「何が」（what the bank is = 銀行が何であるか、不適切）。which は「どちらが」（特定の選択肢がある場合）。", rule: "間接疑問文：疑問詞 + 主語 + 動詞（語順に注意）", kp: ["where the bank is = 銀行がどこにあるか（間接疑問: 疑問詞 + S + V）", "間接疑問の語順: ×where is the bank → ○where the bank is"] },
  { id: "g1588", diff: "lv3", axis: "form", tags: ["eiken2", "causative_make"], stem: "My teacher made me ___ the report again.", ja: "先生は私にレポートを書き直させた。", answer: "rewrite", choices: ["rewrite", "to rewrite", "rewriting", "rewritten", "rewrote"], expl: "使役動詞 make + 目的語 + 動詞原形: make someone do = 「〜に…させる（強制）」。made me rewrite = 「私に書き直させた」。make の後の動詞は原形（to なし）。to rewrite は不定詞（make の後は to なしの原形が来る）。rewriting は現在分詞（分詞構文）。rewritten は過去分詞（受動態の場合）。rewrote は過去形（動詞が2つ並ぶ）。", rule: "使役動詞 make + O + 動詞原形：〜に…させる（強制）", kp: ["made me rewrite = 私に書き直させた（make + O + 原形）", "使役動詞: make（強制）/ let（許可）/ have（手配）/ get（説得・to不定詞）"] },
  { id: "g1589", diff: "lv3", axis: "form", tags: ["eiken2", "perfect_participle_clause"], stem: "___ all her work, she went home.", ja: "仕事をすべて終えて、彼女は家に帰った。", answer: "Having finished", choices: ["Having finished", "Finishing", "Finished", "To finish", "She finished"], expl: "完了分詞構文（Having + 過去分詞）: 主節の動詞より前に完了した動作を表す。Having finished = 「（すでに）終えてから」（完了の意味を持つ分詞構文）。Finishing は現在分詞構文（主節と同時の動作）。Finished は過去分詞（受動の分詞構文 = 終えられた、意味が不自然）。To finish は不定詞（目的・結果の意味になる）。She finished は主節になってしまう（分詞構文の形でない）。", rule: "完了分詞構文：Having + 過去分詞（主節の動作より前に完了）", kp: ["Having finished all her work = 仕事をすべて終えてから（完了分詞構文）", "現在分詞構文（同時）vs 完了分詞構文（前）: Finishing / Having finished"] },
  { id: "g1590", diff: "lv2", axis: "logic", tags: ["eiken3", "relative_adverb_where"], stem: "This is the city ___ I was born.", ja: "ここは私が生まれた都市だ。", answer: "where", choices: ["where", "which", "that", "who", "when"], expl: "関係副詞 where: 先行詞が場所（the city）で、関係節内で「場所」の意味を持つ副詞の役割をする場合は where を使う。where I was born = 「私が生まれた（場所）」。which は関係代名詞（物の先行詞で目的語・主語の役割）。that は関係代名詞（the city that I was born in のような形なら可）。who は人が先行詞の場合。when は時間の先行詞（the time when）。", rule: "関係副詞 where：場所を表す先行詞 + 関係節（in/at which = where）", kp: ["the city where I was born = 私が生まれた都市（関係副詞 where）", "関係副詞: where（場所）/ when（時）/ why（理由）/ how（方法）"] },
  { id: "g1591", diff: "lv3", axis: "logic", tags: ["eiken2", "cleft_sentence"], stem: "___ Tom who broke the window, not Mike.", ja: "窓を割ったのはトムであって、マイクではない。", answer: "It was", choices: ["It was", "He was", "That was", "There was", "It is"], expl: "強調構文（分裂文）: It is/was + 強調する要素 + that/who + 残りの文。It was Tom who broke = 「窓を割ったのはトムだった」（Tom を強調）。It was（過去形）+ Tom（強調対象）+ who（人が先行詞なので who）。He was は通常の主語 + 動詞（強調構文でない）。That was は指示代名詞（強調構文にならない）。There was は存在文（意味が異なる）。It is は現在形（過去の文脈に合わない）。", rule: "強調構文：It is/was + 強調要素 + who/that + 残りの文", kp: ["It was Tom who broke = 割ったのはトムだった（強調構文: It was...who）", "強調構文で人を強調する場合: who（または that）を使う"] },
  { id: "g1592", diff: "lv3", axis: "logic", tags: ["eiken2", "inversion_neither"], stem: "I don't like coffee, and ___ does my brother.", ja: "私はコーヒーが好きではないし、兄もそうだ。", answer: "neither", choices: ["neither", "either", "so", "also", "nor"], expl: "否定の同意（倒置）: neither + 助動詞 + 主語 = 「〜もそうではない」。neither does my brother = 「兄もコーヒーが好きではない」（否定の同意）。either は文末に置く（not...either）。so は肯定の同意（so does my brother = 兄もそうだ、肯定）。also は副詞（倒置形でない）。nor は等位接続詞（nor does my brother も可だが neither の方が口語的）。", rule: "Neither + 助動詞 + 主語：〜もそうではない（否定の同意・倒置）", kp: ["neither does my brother = 兄もそうではない（否定の同意 + 倒置）", "肯定の同意: So do I / So does he ←→ 否定の同意: Neither do I / Neither does he"] }
);
